# fly.toml app configuration file generated for ms-prod-gotenberg on 2024-07-22T20:43:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ms-prod-gotenberg'
primary_region = 'lax'

[build]
  image = 'ozitrance/gotenberg:8.8.1'

[env]
  PORT = '3000'

[[vm]]
  size = 'shared-cpu-1x'
